pool:
  vmImage: 'windows-2019'

trigger:
  - master

pr: none

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: NuGetCommand@2
  displayName: Pack Packages
  inputs:
    command: 'pack'
    includeSymbols: true
    arguments: '--configuration Release'